### ISSUE TITLE
CSS Table issue

### ISSUE THREAD

**Issue by themeix** [pacemkr/ghost-theme#1]
Please use the following css in your code injection area

```
<style>
.single-content table td, .single-content table th {
    border: 1px solid #979797;
    padding: 5px;
}

.single-content table {
    width: 100%;
    margin-bottom: 20px;
}

.single-content table th {
    background: #e2efda;
}
/* To remove homepage background opacity */
.slider-wrapper:after {
opacity:0!important
}
</style>
```

**Comment by lpcarignan** [comment]
It works if I put it in my code injection area of each page.

I would like to integrate it into my custom code of my Ghost theme. I put  it in style.css but it isn't integrated. To I have to run a command to re-compile style.min.css which is the file read by Ghost?

**Comment by themeix** [comment]
Yes... 
use the command, `npm install ` and then `gulp` then update the file style.scss add the code in the very bottom of that file

**Comment by lpcarignan** [comment]
I'd like to put this code snippet in a place where I don't have to always copy it back at the bottom of style.scss.

I tried modifying style.css. For example, I changed the opacity of .slider-wrapper:after to 0!important. When I run gulp, it resets this value.

Where can I change the original code in the .css files so I don't have to always add it to style.scss everytime.

**Comment by lpcarignan** [comment]
Please ignore my previous comment. I discovered the source file is style.scss. When running gulp, it uses this file to generate the rest.

**Comment by themeix** [comment]
Great.. I was planning to make a video for you..

**Comment by themeix** [comment]
Please follow that, https://youtu.be/qsdsz8yrF2Q
Same process for the ghost theme file edit
